version: "3.8"

#see https://docs.docker.com/compose/extends/
#to create productive env-container, run `docker-compose -f docker-compose.yml -f docker-compose.prod.yml up`
#run tests: docker-compose -f docker-compose.yml -f docker-compose.prod.yml run web python manage.py test
#TODO: see "Administrative tasks" here: https://docs.docker.com/compose/extends/ -> make backup like this

services:
  backend:
    command: entrypoint_prod.sh
    environment:
       - DJANGO_SETTINGS_MODULE=settings.production #TODO: use settings.production!!!!
    volumes:
      - production_static_data:/vol/web

  proxy:
    build:
      context: ./proxy
    volumes:
      - production_static_data:/vol/static
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  production_static_data:
