version: "3.8"

#see https://forums.docker.com/t/data-directory-var-lib-postgresql-data-pgdata-has-wrong-ownership/17963/26
services:
  sidb:
    container_name: siddata_server_db_1
    image: postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=siddata
      - POSTGRES_USER=siddata
      - POSTGRES_PASSWORD=siddata

  backend:
    container_name: siddata_server_backend_1
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - uid=${COMPOSE_UID:-1000}
        - gid=${COMPOSE_GID:-1000}
    ports:
      - "8000:8000"
    depends_on:
      - sidb
    environment:
     - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-settings.development}
    restart: always
    command: entrypoint_dev.sh
